### ISSUE TITLE
Synonyms on production

### ISSUE THREAD

**Issue by tschimbr** [eonum/drg-search#39]
If we have more than ~8'000 lines in our synonym file I encounter the following error when invoking Model.reindex:

```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"already exists","index":"adrgs_production_20160607161029356"}],"type":"index_already_exists_exception","reason":"already exists","index":"adrgs_production_20160607161029356"},"status":400}
    from /usr/local/rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/client.rb:128:in `perform_request'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/elasticsearch-api-1.0.17/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/elasticsearch-api-1.0.17/lib/elasticsearch/api/actions/indices/create.rb:77:in `create'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/searchkick-1.3.0/lib/searchkick/index.rb:11:in `create'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/searchkick-1.3.0/lib/searchkick/index.rb:139:in `create_index'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/searchkick-1.3.0/lib/searchkick/index.rb:165:in `reindex_scope'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/searchkick-1.3.0/lib/searchkick/model.rb:53:in `searchkick_reindex'
    from (irb):1
    from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    from /home/arun/drg-search/bin/rails:8:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
    from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by tschimbr** [comment]
It should not be an issue with the entries in the file. Lines 8'000 - 10'000 are processed fine when in a separate file with less than 8'000 lines.

**Comment by tschimbr** [comment]
No longer a problem as we have a reduced synonym list of only ~4k entries.
